### ISSUE TITLE
How to run the pretrained model?

### ISSUE THREAD

**Issue by xiaofeiwu** [aiff22/DPED#1]
How to run the pre-trained model? It seems that there is no tutorial command.

**Comment by aiff22** [comment]
Hi,
Section **```5. Test the provided pre-trained models```** describes how to do this. Besides that, you can also download the pre-trained models and standalone code to run them from [here](https://drive.google.com/file/d/0BwOLOmqkYj-jcnZpaDR0dU9XMm8/view?usp=sharing).
