### ISSUE TITLE
add addition parameter in generator

### ISSUE THREAD

**Issue by pribadihcr** [aiff22/DPED#10]
Hi @aiff22,

Why in your code enhanced = tf.nn.tanh(conv2d(c11, W12) + b12) * 0.58 + 0.5,
there is * 0.58 + 0.5. there is an explanation?

Thanks

**Comment by aiff22** [comment]
Hi @pribadihcr,

```* 0.58 + 0.5``` is used to map the values of the processed image back to [0, 1] range.
