### ISSUE TITLE
Question about tf.nn.tanh(x) * 0.58 + 0.5

### ISSUE THREAD

**Issue by scott89** [aiff22/DPED#13]
Dear @aiff22, 
In the generator,  I am confused that why not use  * 0.5 +0.5 to map the values to the range of  [0, 1].   'tanh(x)*0.58 + 0.5' will map the values to the range [-0.08, 1.08].  Thank you!

**Comment by yifanw90** [comment]
I am also confused with that.

**Comment by aiff22** [comment]
Hello

Since ```tanh(x)``` function is mapping from (-∞, +∞) to (0, 1), the output of the network should be close to ±∞ to get strictly 0 or 1. Using a wider interval allows to fix both boundaries constant (instead of ±∞).

**Comment by scott89** [comment]
Thanks for the answer!
