### ISSUE TITLE
A little doubt that what do the coefficients represent for

### ISSUE THREAD

**Issue by Melody-doudou** [aiff22/DPED#15]
Hi, just a little doubt that what do the coefficients of the model definition of the generator (that is, 0.58 and 0.5, separately) represent for. Thanks. 

    enhanced = tf.nn.tanh(conv2d(c11, W12) + b12) * 0.58 + 0.5

**Comment by aiff22** [comment]
Hi @Melody-doudou 

Please take a look at the description provided here: #13
