### ISSUE TITLE
Quality improvement query

### ISSUE THREAD

**Issue by ved27** [aiff22/DPED#16]
Hi,

I ran the iphone,sony,blackberry pre-trained models on some sunset and visually attractive images.

The iphone model produces decent outputs but the other two remove the sharpness and almost the output is smooth

Can I know few hyper parameter settings I could try in training the model so that the output has good texture and the input image is not degraded in case of them images taken in decent light conditions ?

**Comment by aiff22** [comment]
@ved27, the code in this repository is using the same hyper-parameters that were used to pre-train the provided models. Please note that the characteristics of the resulting model will heavily depend on the training dataset: the learned mapping is aimed at improving the properties of the photos captured with a particular device, not general images. This explains your observations described above.
