### ISSUE TITLE
The loss curve about the texture loss

### ISSUE THREAD

**Issue by JerryLeolfl** [aiff22/DPED#19]
@aiff22 , I ran the code, and I found that the loss curve about the texture loss has obvious concussion. Is that normal？

**Comment by zhaoxin111** [comment]
@JerryLeolfl Hi, I am also confused about the texture loss code. In train_model.py, the texture loss is ok when train thegenerator network. However, the targets are reverse when train the discriminative network.

**Comment by aiff22** [comment]
@JerryLeolfl, yes, this is a normal behavior. Note that the texture loss is opposite to the classification accuracy of the discriminator network. If the discriminator fails to distinguish between the "true" and "enhanced" images, this means that its predictions are true in ~50% of cases, which corresponds to the minimum value of the texture loss. The fluctuations of this prediction accuracy causes the concussions and fluctuations of the texture loss.
