### ISSUE TITLE
bug in vgg.py ?

### ISSUE THREAD

**Issue by jxwjasonborne** [aiff22/DPED#2]
Hi:
    I download the training data and vgg net, run the train_model.py using the given command.
    But I encountered the following error:

    kernels, bias = weights[i][0][0][0][0]
    ValueError: too many values to unpack

So, am I wrong somewhere with the code ?

Thank you very much !

**Comment by aiff22** [comment]
Hi,
This error usually happens when the vgg-19 model has incorrect format. Did you use the provided imagenet-vgg-verydeep-19.mat network (https://drive.google.com/file/d/0BwOLOmqkYj-jMGRwaUR2UjhSNDQ/view?usp=sharing), or did you download it from other sources?

**Comment by jxwjasonborne** [comment]
@aiff22 
Maybe I downloaded it from other sources, since I found the file size did not match. I will download the provided file and try again.
Thanks very much.
