### ISSUE TITLE
consult for the dataset

### ISSUE THREAD

**Issue by JiaqianLi** [aiff22/DPED#21]
hello, thank you for sharing your work.  I downloaded the dataset from the link you gave, but found that the given dataset was not aligned. The test set full_size_test_images only has sony, iphone, blackberry, but no canon, can provide full_size aligned data sets for training and testing. If it is convenient, it can be sent to my mailbox 770534632@qq.com. Thank you.

**Comment by aiff22** [comment]
@JiaqianLi, you can download the entire [DPED dataset](http://people.ee.ethz.ch/~ihnatova/index.html#dataset) to get full-resolution Canon images. Please note that it is not really possible to align full images due to the significant difference in optics and sensors used in the considered devices.

**Comment by Oktai15** [comment]
@aiff22 I want to test my model with models which were in PRIM 2018 challenge. I have 2 questions:

1. PSNR/MS-SSIM were calculated on patches (100x100) or HD images (1280x720)? I mean final result [here](http://openaccess.thecvf.com/content_ECCVW_2018/papers/11133/Ignatov_PIRM_Challenge_on_Perceptual_Image_Enhancement_on_Smartphones_Report_ECCVW_2018_paper.pdf) 
2. It was private data or you used the same test_data that was provided in archive with train datasets? I mean if I can compare my score . on `test_data` folder with scores in paper about PRIM.

**Comment by aiff22** [comment]
Hi @Oktai15,

1. PSNR and MS-SSIM scores were calculated on the patches, not full-resolution images.

2. We used private data to test the models submitted by challenge participants.
