### ISSUE TITLE
test model, but error

### ISSUE THREAD

**Issue by billqu01** [aiff22/DPED#23]
I run the cmd, but error.
python test_model.py model=iphone_orig test_subset=full resolution=orig use_gpu=true
the error below, how should I do?
Testing original iphone model, processing image 1.jpg
Traceback (most recent call last):
  File "test_model.py", line 50, in <module>
    image = np.float16(misc.imresize(misc.imread(test_dir + photo), res_sizes[phone])) / 255
AttributeError: 'module' object has no attribute 'imresize'

**Comment by aiff22** [comment]
@billqu01, 'imresize' function was deprecated and removed in SciPy 1.2.0. You can either install an earlier version of SciPy or use Pillow library for image resizing instead.
