### ISSUE TITLE
Image size becomes larger

### ISSUE THREAD

**Issue by Jason-xin** [aiff22/DPED#25]
When I test images with resolution=orig，the size of enhanced images becomes larger than original images.
e.g. original size is 295KB while enhanced size is 1.1MB, why becoming so large?

Another question: The speed of inference is 60s per image on my macbookpro, so slow?

**Comment by Jason-xin** [comment]
Maybe convert format to png.... When I convert format to jpg, it becomes similar size as the original.

**Comment by aiff22** [comment]
Hi @Jason-xin,

Yes, you are right, the difference is caused by different file formats (png vs. jpeg).
The inference is so slow because you are running it on a CPU (unfortunately, TensorFlow cannot use macbook GPUs).
