### ISSUE TITLE
Quite slow on my mac machine for given models.

### ISSUE THREAD

**Issue by Dinesh21Kumar** [aiff22/DPED#27]
I am using the command mentioned.
python test_model.py model=iphone_orig test_subset=full resolution=orig use_gpu=false

But for a single image, it is taking around ~24 seconds. Is there any way to improve the time?

**Comment by aiff22** [comment]
@Dinesh21Kumar, since the model is quite big, it is not possible to significantly reduce the run time when using CPU. The only way to do this is to install TensorFlow build optimized for your CPU using [Conda](https://docs.conda.io/en/latest/).
