### ISSUE TITLE
Hi, after reading the source code, I couldn't save the models into .pb file. could  you tell me how to save the models into .pb files and load it? Thanks.

### ISSUE THREAD

**Issue by Guein** [aiff22/DPED#3]

**Comment by aiff22** [comment]
Hi,
The provided code saves only CNN weights. You can find the explanation on how to save the whole graph in the following tutorials:

https://www.tensorflow.org/api_docs/python/tf/train/write_graph

https://blog.metaflow.fr/tensorflow-how-to-freeze-a-model-and-serve-it-with-a-python-api-d4f3596b3adc

https://stackoverflow.com/questions/38947658/tensorflow-saving-into-loading-a-graph-from-a-file

**Comment by naveedkhan2019** [comment]
> _No description provided._

If you have got .pb file of their trained models then please share it with me I need it urgently. Thanks
