### ISSUE TITLE
I want to change the network to single channel

### ISSUE THREAD

**Issue by LH-git-hub** [aiff22/DPED#30]
Has anyone tried to change the DPED network to a single channel network？

**Comment by aiff22** [comment]
@LH-git-hub, you can simply change [here](https://github.com/aiff22/DPED/blob/e30bdebe2b8285e7c375626f5fc659d60b2e3a90/models.py#L8) the size of the filter from [9, 9, 3, 64] to [9, 9, 1, 64].
