### ISSUE TITLE
Why "enhanced = tf.nn.tanh(conv2d(c11, W12) + b12) * 0.58 + 0.5"?

### ISSUE THREAD

**Issue by JarvisUSTC** [aiff22/DPED#31]
I don't understand the appearence of 0.58 and 0.5. Also I can't find them in the paper。May @aiff22 can explain it? Thanks!

**Comment by aiff22** [comment]
Hi @JarvisUSTC,

Please find the answer to your question [here](https://github.com/aiff22/DPED/issues/13#issuecomment-402696926).
