### ISSUE TITLE
感觉不如opencv一行代码提升效果明显

### ISSUE THREAD

**Issue by liuxufenfeiya** [aiff22/DPED#37]
cv2.normalize(img,dst=None,alpha=350,beta=10,norm_type=cv2.NORM_MINMAX)
各位可以测一下，我这边是测了发现正常环境opencv和DPED没差多少
但是在极限弱光环境下，opencv的对比度拉升要好于DPED
![微信图片编辑_20210421172552](https://user-images.githubusercontent.com/33931180/115531103-face9900-a2c6-11eb-91d7-14f28c89d20c.jpg)
左边原图，中间opencv，右边DPED

**Comment by aiff22** [comment]
Hi @liuxufenfeiya,

DPED was trained for three particular camera sensor models. If you apply it to some random images - the results clearly won't be perfect.
