### ISSUE TITLE
Comparison with APE that is source-ignorant?

### ISSUE THREAD

**Issue by JonQKim** [aiff22/DPED#38]
Thank you for sharing great work.
I'd like to ask a question about the comparison with APE for evaluation.

APE is a general purpose enhancement tool that does not know from what camera source the image was taken.
In my opinion, the better quality of DPED partly comes from the fact that it was trained only for specific camera sources.

Would you give me your thoughts on my opinion?
And would you share another evaluation result if you conducted training a network with all the camera sources together?

**Comment by aiff22** [comment]
> APE is a general purpose enhancement tool that does not know from what camera source the image was taken.

Yes, that's correct, but we will have the same situation with any standard image enhancement tool not using specific ML models trained for some particular camera sensors. Therefore, one can either compare the solution to such source ignorant software or to the corresponding deep learning-based architectures trained on the same data. Both options are considered in this paper.
