### ISSUE TITLE
The order of leaky_relu layer and BN layer for D-net

### ISSUE THREAD

**Issue by YvonneYuan** [aiff22/DPED#5]
Hi there,

I am looking at your code and trying to reproduce your WESPE paper. I found in the function _conv_layer() in models.py file, the BN layer is after leaky_relu layer, which is different from what other people usually do (BN first, then relu layer).   Is there any special reason you do so? 

BTW, will the code for WESPE paper will be released?

Thanks a lot.

Best,
Yvonne

**Comment by aiff22** [comment]
Hi Yvonne,

Our experiments revealed that the order of BN and leaky_relu layer does not significantly affect the network performance, thus this order was chosen.

WEPSE code will be released upon the publication.

**Comment by DaPenggg** [comment]
@aiff22 WEPSE code ?where is it?
