### ISSUE TITLE
How to port resnet(image) onto android devices.

### ISSUE THREAD

**Issue by nagendra-sharman** [aiff22/DPED#6]
Please share some insight on how to port resnet(image) from model.py onto android devices.
I have trained and saved a model, but the model requires the output from resnet(image) as input. Not sure how to do that on android.

Thanks in advance.

**Comment by aiff22** [comment]
Hi @nagendra-sharman,

Porting this network on android devices is a separate task that is out of scope of this project.
For more information on how to do this please refer to the official tensorflow-mobile repository:
https://github.com/tensorflow/tensorflow/tree/r1.6/tensorflow/examples/android
