### ISSUE TITLE
Is there code of preprocessing data?

### ISSUE THREAD

**Issue by jinjiin** [aiff22/DPED#7]
I have some questions about extracting patches bases on cross-correlation metrics @aiff22

**Comment by qicathetine** [comment]
Is there any detail instruction about extracting patches @aiff22? Thank you

**Comment by XSLXANDY** [comment]
> Hi,
> 
> A detailed description of the patch extraction algorithm is provided in the paper. Mainly, in consists of two parts:
> 
> 1. Rough image alignment using SIFT features (you can use this code as a reference: http://www.vlfeat.org/install-matlab.html)
> 2. Extracting precisely aligned patches from pre-aligned images obtained on the previous step using a sliding window approach. Basically, two sliding windows are shifting in parallel along a DSLR-phone image pair, and the position of one window is additionally adjusted by small shifts and rotations to maximize cross-entropy between the observed patches. If this cross-entropy is larger than a threshold (0.9), two current patches (from DSLR and phone image) are added into the training dataset.
> 
> Hope this helps.

Hi, aiff22,
You mentioned that the position of one window is additionally adjusted by small shifts and rotations. However, I still don't understand how to do it. Can you specify the details?

**Comment by Jason-xin** [comment]
> 2\. cross-entropy

Can you provide the Extracting code ?
